#!/bin/sh

cd "$(dirname "$0")/.."

test -z "$NODE_ENV" &&
  export NODE_ENV='development'

if [ "$NODE_ENV" = "development" ]; then
  /Users/rob/.nvm/versions/node/v6.9.4/lib/node_modules/forever/bin/forever -f config/forever/development.json
else
  /Users/rob/.nvm/versions/node/v6.9.4/lib/node_modules/forever/bin/forever start config/forever/production.json
fi
